services:
  - type: web
    name: ğŸ§ ğ˜¼ğ™‰ğ˜¼ğ™‰ğ™”ğ˜¼ âœ˜ ğ™ˆğ™ğ™ğ™„ğ˜¾ â›
    env: python
    plan: free
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    startCommand: bash start
